### ISSUE TITLE
서버로 내 계정 설정 동기화 기능

### ISSUE THREAD

**Issue by Willowslab** [Willowslab/library.willowslab.net#3]
서버 재원이 충분하지 않은 관계로 미뤄지고 있지만

하늘빛은하가 내부적으로 작업중

**Comment by isairz** [comment]
계정 내 설정이라 함은 단축키/팻목록 을 말하는 것인가요?
개인적으로 사용하던 마비노기 단축키 클라우드를 배포 준비 중인데, 기능이 겹치는 것 같아 문의 드립니다.

**Comment by Willowslab** [comment]
@isairz 모든 마비노기 설정 폴더를 압축해 서버로 업로드하는 방식이었으나, 서버 가용성의 문제로 미뤄지고 있습니다. 현재 본 기능의 개발은 하늘빛은하가 진행중에 있습니다.

**Comment by Willowslab** [comment]
@isairz 본 프로그램에 직접 개발해 넣어주신다면 서버 공간을 확보하여 할당해드리도록 하겠습니다.

**Comment by isairz** [comment]
메일 필터링이 잘못 걸려 있어서 답변이 늦었네요.

버들랩을 사용하지 않는 사람도 사용 할 수 있도록 별도의 클라이언트를 만들고, API를 버들랩에도 제공하도록 하겠습니다.
